### ISSUE TITLE
org.bouncycastle.tls.TlsFatalAlert: internal_error(80)

### ISSUE THREAD

**Issue by srk12318** [bcgit/bc-java#1292]
Hi,

Java - 1.8

My application deployed on 2 weblogic managed servers. One M.server in one Linux host and another M.server is in different linux host.

Earlier my code  worked on both managed servers. But suddenly

My code is working fine on one of the M.server and not working another managed server and giving below error. We didn't do any changes to both m.servers recently.

org.bouncycastle.tls.TlsFatalAlert: internal_error(80)
        at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:395)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:354)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)		
Caused by: java.lang.IllegalArgumentException: unknown HashAlgorithm: UNKNOWN(8)
        at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.getDigestName(Unknown Source)
        at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.createHash(Unknown Source)
        at org.bouncycastle.tls.DeferredHash.checkTrackingHash(Unknown Source)
        at org.bouncycastle.tls.DeferredHash.trackHashAlgorithm(Unknown Source)
        at org.bouncycastle.tls.TlsUtils.trackHashAlgorithms(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
        at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)

**Comment by srk12318** [comment]
Please someone can help

**Comment by srk12318** [comment]
01-Dec-2022 17:22:07,074 o'clock GMT> <Debug> <org.bouncycastle.jsse.provider.ProvTlsClient> <hostname> <managed3_domain> <WS-Worker-xxx-98> <<anonymous>> <> <fed8222d-dd29-48bd-82a3-a35600493c85-0000001a> <1669915327074> <[severity-value: 128] [rid: 0:329] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000000> <[org.bouncycastle.jsse.provider.ProvTlsClient:notifySelectedCipherSuite] Client notified of selected cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384>
<01-Dec-2022 17:22:07,360 o'clock GMT> <Warning> <org.bouncycastle.jsse.provider.ProvTlsClient> <hostname> <managed3_domain> <WS-Worker-xxx-98> <<anonymous>> <> <fed8222d-dd29-48bd-82a3-a35600493c85-0000001a> <1669915327360> <[severity-value: 16] [rid: 0:329] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000000> <Client raised fatal(2) internal_error(80) alert: Failed to read record
java.lang.IllegalArgumentException: unknown HashAlgorithm: UNKNOWN(8)

**Comment by srk12318** [comment]
I have upgraded jars to 1.61 but still getting algorith exemption

**Comment by peterdettman** [comment]
The latest version of the jars is 1.72 (https://www.bouncycastle.org/latest_releases.html). Updating to the latest should resolve the issue.

**Comment by srk12318** [comment]
> The latest version of the jars is 1.72 (https://www.bouncycastle.org/latest_releases.html). Updating to the latest should resolve the issue.

Hi Peter

Issue still persists even after upgrading to latest jars.

In other managed server where it is working fine even having 1.59 jars

**Comment by peterdettman** [comment]
Issues around not ignoring unknown HashAlgorithm values were solved. Remaining problems likely to be library version conflicts or classpath issue.
