### ISSUE TITLE
UnsatisfiedLinkError for libbc-probe.so while upgrading to BC FIPS 2.1 from BC FIPS 2.0

### ISSUE THREAD

**Issue by saritha3h** [bcgit/bc-java#1987]
I am trying to upgrade my springboot app to use BC FIPS 2.1 from BC FIPS 2.0 . The app fails to start and throws the below exception.

Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/bc-fips-jni4pv701a2ie-libs/libbc-probe.so: /tmp/bc-fips-jni4pv701a2ie-libs/libbc-probe.so: failed to map segment from shared object [in thread "background-preinit"]
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1957)
        at org.bouncycastle.crypto.fips.NativeLoader$2.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.bouncycastle.crypto.fips.NativeLoader.loadDriver(Unknown Source)
        at org.bouncycastle.crypto.fips.FipsStatus.isReady(Unknown Source)
        at org.bouncycastle.crypto.CryptoServicesRegistrar.getDefaultMode(Unknown Source)
        at org.bouncycastle.crypto.CryptoServicesRegistrar.<clinit>(Unknown Source)
        at org.bouncycastle.jcajce.provider.ProvSecureHash$MD5.configure(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at java.base/sun.security.jca.ProviderConfig$ProviderLoader$1.run(ProviderConfig.java:407)
        at java.base/sun.security.jca.ProviderConfig$ProviderLoader$1.run(ProviderConfig.java:404)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/sun.security.jca.ProviderConfig$ProviderLoader.legacyLoad(ProviderConfig.java:404)
        at java.base/sun.security.jca.ProviderConfig$ProviderLoader.load(ProviderConfig.java:369)
        at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:254)
        at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:248)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.base/sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:248)
        at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:226)
        at java.base/sun.security.jca.ProviderList.loadAll(ProviderList.java:317)
        at java.base/sun.security.jca.ProviderList.removeInvalid(ProviderList.java:334)
        at java.base/sun.security.jca.Providers.getFullProviderList(Providers.java:186)
        at java.base/java.security.Security.getProviders(Security.java:433)
        at java.base/java.security.Security.getAlgorithms(Security.java:1058)
        at org.apache.catalina.util.SessionIdGeneratorBase.<clinit>(SessionIdGeneratorBase.java:48)
        at org.apache.catalina.authenticator.AuthenticatorBase.<init>(AuthenticatorBase.java:190)
        at org.apache.catalina.authenticator.NonLoginAuthenticator.<init>(NonLoginAuthenticator.java:31)
        at org.springframework.boot.autoconfigure.BackgroundPreinitializer$TomcatInitializer.run(BackgroundPreinitializer.java:202)
        at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.runSafely(BackgroundPreinitializer.java:120)
        at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.run(BackgroundPreinitializer.java:113)
        at java.base/java.lang.Thread.run(Thread.java:840)

        

Security.provider file is 
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS

There is no file in  the path /tmp/bc-fips-jni4pv701a2ie-libs/ . Is there any other libraries that needs to be installed along with bc-fips 2.1.0 or is there anything missing in the classpath?

**Comment by mwcw** [comment]
Hi, 

What is the version of spring boot, the architecture of the CPU and the OS you are using please?

Thanks

MW

**Comment by mwcw** [comment]
Ok thanks,

At this stage I am not going to be able to investigate this until early next week.

MW

**Comment by dghgit** [comment]
Try the fix given here:

https://github.com/bcgit/bc-java/issues/1538#issuecomment-2547021180

**Comment by saritha3h** [comment]
We are using BC-FIPS 2.0 with Spring Boot 3.2 and haven't encountered any issues. The problem only occurred after upgrading to BC-FIPS 2.1.

**Comment by dghgit** [comment]
The .so files used by BC-FJA 2.1 create an additional stress point on finding a physical path. Have you tried the solution suggested?

**Comment by anandakshay44** [comment]
its java 17

**Comment by dghgit** [comment]
Hmmm. Okay, is there anything automatically clearing /tmp - the JNI support requires the use of the external .so files, there's no way to load them without storing them on disk somewhere. If they get removed, it will error.

**Comment by dghgit** [comment]
Are there any restrictions on LD_LIBRARY_PATH?

**Comment by mwcw** [comment]
Hi,

Is the temporary directory on the host mounted in such a way that it prevents execution?

That is,  "noexe" is set.

Something to try would be to change the location of the java temp dir by setting it to a different directory.

java -Djava.io.tmpdir=$TEMP_DIR -jar my-app.jar

MW

**Comment by saritha3h** [comment]
The issue was resolved by changing the temp directory to a different location. Thank you so much for your help!

**Comment by winfriedgerlach** [comment]
@saritha3h @mwcw @dghgit so ticket can be closed as completed, right?

**Comment by dghgit** [comment]
Yes.

**Comment by dghbk** [comment]
I think this is properly fixed in 2.1.1, which is still under submission so only currently in early access.

**Comment by rahul-ch** [comment]
thanks for replying. Any idea by when this will be submitted and ready to use.

**Comment by MadhusudanMI** [comment]
Hi David,

I am using BC-FIPS 2.1.2. The reported issue still persist.

Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/bc-fips-jni_70592832932/libbc-probe.so: /tmp/bc-fips-jni_70592832932/libbc-probe.so: failed to map segment from shared object [in thread "background-preinit"]
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at org.bouncycastle.crypto.fips.NativeLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.bouncycastle.crypto.fips.NativeLoader.loadDriver(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsStatus.isReady(Unknown Source)
	at org.bouncycastle.crypto.CryptoServicesRegistrar.getDefaultMode(Unknown Source)
	at org.bouncycastle.crypto.CryptoServicesRegistrar.<clinit>(Unknown Source)
	at org.bouncycastle.jcajce.provider.ProvSecureHash$MD5.configure(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)

Could you please let us know if the above fix is available as part of the product yet?

**Comment by dghgit** [comment]
Is noexe set on /tmp?

**Comment by dghgit** [comment]
No exec isn't something that can be "fixed" (if it was you'd want to speak to your OS vendor)... Fixed in this context was the introduction of org.bouncycastle.native.loader.install_dir which gave fine grain control on the loader as not everyone could override java.io.tmpdir
