### ISSUE TITLE
Maven dependency missing on (at least) `bcutil-jdk18on` with version 1.80

### ISSUE THREAD

**Issue by cobexer** [bcgit/bc-java#2096]
> Somehow the maven addition got missed. I've added it to the list. 

 _Originally posted by @dghgit in [#1977](https://github.com/bcgit/bc-java/issues/1977#issuecomment-2623416196)_

**Comment by dghgit** [comment]
This should now be fixed in BC 1.81 which has just been published.

**Comment by ryanjbaxter** [comment]
@dghgit I still don't see 1.81 in maven central https://mvnrepository.com/artifact/org.bouncycastle/bcutil-jdk18on

**Comment by ryanjbaxter** [comment]
Thanks!  Seems like it is there now.
