### ISSUE TITLE
bctls: Nullpointer exception in TlsServerProtocol on renegotiation

### ISSUE THREAD

**Issue by flako-dd** [bcgit/bc-java#842]
We integrated bctls as Provider in our TLS-Server (jetty 9.4.31.v20200723, protocol version TLSv1.2). When a client tries to renegotiate, the server responds with "SSL alert number 80" which indicates an internal error. On the server side, we see a NullPointerException in the logs.

 We reproduced the exception with ```bc-java/tls/src/test/java/org/bouncycastle/tls/test/TlsServerTest.java```. There, we observe that in the class  TlsServerProtocol at the line 873 the server tries to access an object which is null at that moment. The expected behaviour is that the server checks the variable for a valid value and returns an appriopriate message.

Stacktrace:
```
TLS server raised alert: fatal(2), internal_error(80)
> Failed to read record
java.lang.NullPointerException
    at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(TlsServerProtocol.java:873)
    at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:620)
    at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:516)
    at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:232)
    at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:768)
    at org.bouncycastle.tls.TlsProtocol.readApplicationData(TlsProtocol.java:731)
    at org.bouncycastle.tls.TlsInputStream.read(TlsInputStream.java:29)
    at org.bouncycastle.util.io.Streams.pipeAll(Streams.java:114)
    at org.bouncycastle.tls.test.TlsServerTest$ServerThread.run(TlsServerTest.java:64)
Exception in thread "Thread-74" java.lang.RuntimeException: org.bouncycastle.tls.TlsFatalAlert: internal_error(80)
    at org.bouncycastle.tls.test.TlsServerTest$ServerThread.run(TlsServerTest.java:69)
Caused by: org.bouncycastle.tls.TlsFatalAlert: internal_error(80)
    at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:796)
    at org.bouncycastle.tls.TlsProtocol.readApplicationData(TlsProtocol.java:731)
    at org.bouncycastle.tls.TlsInputStream.read(TlsInputStream.java:29)
    at org.bouncycastle.util.io.Streams.pipeAll(Streams.java:114)
    at org.bouncycastle.tls.test.TlsServerTest$ServerThread.run(TlsServerTest.java:64)
Caused by: java.lang.NullPointerException
    at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(TlsServerProtocol.java:873)
    at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:620)
    at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:516)
    at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:232)
    at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:768)
    ... 4 more
```
 Components used for the test:

 Client:
- OpenSSL version 1.1.1f
- testssl.sh version 3.0

Server:
- BouncyCastle version 1.67
- OpenJDK version 11.0.9.1

 Reproduce the exception:

1. Run TlsServerTest.java
-- default port: 5556
2. run openssl s_client:
-- $ openssl s_client -connect 127.0.0.1:5556 -reconnect -no_ticket
3. Type "R" and return to renegotiate
-- output: [...]: SSL alert number 80

To test with testssl.sh run:
$ ./testssl.sh -R 127.0.0.1:5556
-- The results are displayed green, but server throws NullPointerException

If you need any further Information please let me know.

**Comment by peterdettman** [comment]
This should be fixed in 168b01, available from https://downloads.bouncycastle.org/betas/ . However please note that our TLS implementation does not support renegotiation, other than to refuse it via a no_renegotiation alert.

**Comment by flako-dd** [comment]
okay thank you for the update, i forgot to check the current betas, i will try to reproduce it there.
The expected behaviour is no_renegotiation, correct. I just wanted to report the server side Exception.

**Comment by flako-dd** [comment]
So the current master HEAD 66d368d still shows the same exception and the beta bctls-jdk15on-168b01 ,where i am not sure which revision this correlates to, produces the same issue.

**Comment by peterdettman** [comment]
@flako-dd  I'm just revisiting this and cannot see the exception using the proposed openssl renegotiation test. Are you still seeing this issue (on say 1.69 or the latest beta - 169b04 at present)?

**Comment by flako-dd** [comment]
I retested it and the Issue has been fixed between tags r1rv67 and r1rv68, current master works as well.
Thank you!
