### ISSUE TITLE
X25519PublicKeyParameters.<init> exception

### ISSUE THREAD

**Issue by tkohegyi** [bcgit/bc-java#862]
Using 1.68, OpenJdk 13, apache httpClient v 4.5.12

I see the following exception **randomly** (so sometimes happens sometimes not, same code, same JDK, just the time is different) :

It caused here:
https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/params/X25519PublicKeyParameters.java

```
public X25519PublicKeyParameters(byte[] buf, int off)
    {
        super(false);

        System.arraycopy(buf, off, data, 0, KEY_SIZE);   //here the exception occurs
    }
```

Exception:
```
javax.net.ssl.SSLException: arraycopy: last source index 32 out of bounds for byte[31]
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1652)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:443)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:191)
        at org.apache.http.impl.conn.BasicHttpClientConnectionManager.upgrade(BasicHttpClientConnectionManager.java:325)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:428)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at...

        Caused by:
        java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 32 out of bounds for byte[31]
            at java.base/java.lang.System.arraycopy(Native Method)
            at org.bouncycastle.crypto.params.X25519PublicKeyParameters.<init>(Unknown Source)
            at org.bouncycastle.jcajce.provider.asymmetric.edec.KeyAgreementSpi.engineDoPhase(KeyAgreementSpi.java:163)
            at java.base/javax.crypto.KeyAgreement.doPhase(KeyAgreement.java:579)
            at java.base/sun.security.ssl.KAKeyDerivation.t13DeriveKey(KAKeyDerivation.java:104)
            at java.base/sun.security.ssl.KAKeyDerivation.deriveKey(KAKeyDerivation.java:63)
            at java.base/sun.security.ssl.ServerHello$T13ServerHelloConsumer.consume(ServerHello.java:1290)
            at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHello(ServerHello.java:1005)
            at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.consume(ServerHello.java:893)
            at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
            at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
            at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
            at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
            at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
            at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460)
            at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368)
            at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
            ... 11 more
```

Could you pls investigate what can cause this?

**Comment by tonywasher** [comment]
The stack is initially confusing, since prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/edec/KeyAgreementSpi.java does not match your stack. However you are using java13 and the multi-release jar inserts prov/src/main/jdk1.11/org/bouncycastle/jcajce/provider/asymmetric/edec/KeyAgreementSpi.java instead which matches your stack in the code which translates JCE 1.11 XDH keys for use by BC.

The failure would appear to be caused by the BigIntegers.asUnsignedByteArray() method which converts a BigInteger to a byte array, BUT crucially removes leading zero bytes if they exist. This leads to a short buffer and index out of bounds exception in the 1 in 256 chance that the leading byte of the key is zero, which matches your scenario.

**Comment by tkohegyi** [comment]
Hi @tonywasher - thanks for the investigation. 
Since this BigIntegers method may cause issue for the other (X448) key too, do you agree that the issue would be fixed by calling the simple toByteArray() method directly, instead of using the BigIntegers class?
So at [KeyAgreementSpi.java](https://github.com/bcgit/bc-java/blob/master/prov/src/main/jdk1.11/org/bouncycastle/jcajce/provider/asymmetric/edec/KeyAgreementSpi.java):
```
           //note - both key might be harmed by BigIntegers.asUnsignedByteArray

           byte[] keyData = Arrays.reverse(jcePub.getU().toByteArray());

            if (keyData.length == X448PublicKeyParameters.KEY_SIZE)
            {
                pub = new X448PublicKeyParameters(keyData, 0);
            }
            else
            {
                pub = new X25519PublicKeyParameters(keyData, 0);
            }
```
?

**Comment by tonywasher** [comment]
Hi @tkohegyi, No I don't agree.

The whole point is that the array derived from the getU() value must be exactly 448 bits long for X448 and 256 bits long for X25519. The method toByteArray() returns the minimum number of bytes required to represent the integer, which may be one byte too long, or may be several bytes too short. The correct function to use is BigIntegers.asUnsignedByteArray(int, BigInteger),
with the length parameter set depending on whether the input key is X448 or X25519.

It should be noted that the same problems occurs with the JCE 1.15 EdEC keys in SignatureSPI.java

I will add a pull request with what I believe is the correct fix

**Comment by tkohegyi** [comment]
thx, @tonywasher

**Comment by peterdettman** [comment]
Merged https://github.com/bcgit/bc-java/pull/866, which should fix this.

It's still unclear to me why SunJSSE gets a KeyAgreement from the BC provider, but (apparently) gets a KeyFactory from somewhere else (presumably SunEC), so that BC has to interact via the XECPublicKey interface instead of just recognizing its own key type. Probably worth understanding in case we're missing some provider algorithm entries or something.

**Comment by denis111** [comment]
I've compiled v1.68 with #866 but the error still occurs randomly with latest OpenJDK 11 also (maybe because of backported  things from 13?).

**Comment by peterdettman** [comment]
There were significant changes beyond what was in #866, this was the merge commit: https://github.com/bcgit/bc-java/commit/650db0c51d598e82847bdc26f4df659e9b8b3314 .

In any case, we now have a new beta (1.69b01) up at https://downloads.bouncycastle.org/betas/ and would certainly appreciate people testing it out on various JDKs.

**Comment by machajdik** [comment]
I had the same issue using 1.68, OpenJdk 11. When using 1.69b03 the error no longer occurs.

**Comment by dghgit** [comment]
Closing as now fixed in https://www.bouncycastle.org/betas

**Comment by peterdemaeyer** [comment]
We're using BC 1.68 since Dec 2020, last week we ran into this issue after upgrading to Red Hat OpenJDK 11.0.11 (for an unknown reason, the issue did not seem to occur with OpenJDK 11.0.8).
Using 1.69b10, the issue was fixed.
We can't (easily) depend on a beta for our release, so I'm wondering if there will soon be a 1.69 GA version available in Maven?

**Comment by dghgit** [comment]
We're currently hoping to ship 1.69 at the start of next week.

**Comment by tkohegyi** [comment]
By using v1.69 the issue has been disappeared - thx for your work @tonywasher @peterdettman.
